services:
  - type: web
    name: vehicle-dashboard-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GITHUB_BRANCH
        value: main
      - key: GITHUB_FILE_PATH
        value: vehicle_data.json
